#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Frog.Resource", IsApplication=true)]

namespace Frog
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int accent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int primary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int primaryDark = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int text = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int window_background = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border_bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bottom_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int corners_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_launcher = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int jpush_ic_richpush_actionbar_back = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int jpush_ic_richpush_actionbar_divider = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int jpush_notification_icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int richpush_btn_selector = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int richpush_progressbar = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int stripes = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tiledstripes = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int top_bg = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int actionbarLayoutId = 2131165193;
			
			// aapt resource value: 0x7f070020
			public const int bt_alias = 2131165216;
			
			// aapt resource value: 0x7f07001e
			public const int bt_tag = 2131165214;
			
			// aapt resource value: 0x7f070024
			public const int bu_setTime = 2131165220;
			
			// aapt resource value: 0x7f070029
			public const int cb_friday = 2131165225;
			
			// aapt resource value: 0x7f070025
			public const int cb_monday = 2131165221;
			
			// aapt resource value: 0x7f07002a
			public const int cb_saturday = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int cb_sunday = 2131165227;
			
			// aapt resource value: 0x7f070028
			public const int cb_thursday = 2131165224;
			
			// aapt resource value: 0x7f070026
			public const int cb_tuesday = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int cb_wednesday = 2131165223;
			
			// aapt resource value: 0x7f07002d
			public const int end_time = 2131165229;
			
			// aapt resource value: 0x7f07001f
			public const int et_alias = 2131165215;
			
			// aapt resource value: 0x7f07001d
			public const int et_tag = 2131165213;
			
			// aapt resource value: 0x7f07000f
			public const int fullWebView = 2131165199;
			
			// aapt resource value: 0x7f070019
			public const int getRegistrationId = 2131165209;
			
			// aapt resource value: 0x7f070000
			public const int icon = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int imgRichpushBtnBack = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int imgView = 2131165196;
			
			// aapt resource value: 0x7f070016
			public const int init = 2131165206;
			
			// aapt resource value: 0x7f07001c
			public const int layout_root = 2131165212;
			
			// aapt resource value: 0x7f070004
			public const int m_icon = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int m_text = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int m_title = 2131165189;
			
			// aapt resource value: 0x7f07001a
			public const int msg_rec = 2131165210;
			
			// aapt resource value: 0x7f070007
			public const int popLayoutId = 2131165191;
			
			// aapt resource value: 0x7f07000e
			public const int pushPrograssBar = 2131165198;
			
			// aapt resource value: 0x7f070018
			public const int resumePush = 2131165208;
			
			// aapt resource value: 0x7f07000a
			public const int rlRichpushTitleBar = 2131165194;
			
			// aapt resource value: 0x7f070021
			public const int setStyle0 = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int setStyle1 = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int setStyle2 = 2131165219;
			
			// aapt resource value: 0x7f07001b
			public const int setting = 2131165211;
			
			// aapt resource value: 0x7f07002c
			public const int start_time = 2131165228;
			
			// aapt resource value: 0x7f070017
			public const int stopPush = 2131165207;
			
			// aapt resource value: 0x7f070002
			public const int text = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int time = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int title = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int tvRichpushTitle = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int tv_appkey = 2131165201;
			
			// aapt resource value: 0x7f070014
			public const int tv_device_id = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int tv_imei = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int tv_package = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int tv_regId = 2131165200;
			
			// aapt resource value: 0x7f070015
			public const int tv_version = 2131165205;
			
			// aapt resource value: 0x7f070008
			public const int wvPopwin = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int customer_notitfication_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int customer_notitfication_layout_one = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int jpush_popwin_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int jpush_webview_layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int push_set_dialog = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int set_push_time = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int alias_hint = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int error_alias_empty = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int error_network = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int error_style_empty = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int error_tag_empty = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int error_tag_gs_empty = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int hello = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int logining = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int setting_su = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int style_hint = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int tag_hint = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060003
			public const int MyDialogStyle = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int push_alias = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int push_style = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int push_tag = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
